### ISSUE TITLE
add github url

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [RedHatQE/wait_for#9]

**Comment by psav** [comment]
Where would you like this to be added?

**Comment by blag** [comment]
@psav Almost all other PyPI packages specify this in `setup.py` or `setup.cfg`, so the PyPI project page can link to this repository.

Similar to how you did it in [riggerlib's `setup.py` file](https://github.com/psav/riggerlib/blob/a2e939ced65f914991a503ac433115ec2d161515/setup.py#L24):

```python
setup(
    name="riggerlib",
    ...
    url="https://github.com/psav/riggerlib",
)
```

Adding the `url` attribute helps other developers troubleshoot issues (especially packaging/dependency/version issues!), report bugs, and submit PRs.

Otherwise, it is almost impossible to find this repository organically.
